language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - "8"
  - "10"
  - "12"

before_install:
  # Install latest Yarn.
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --force

script:
  - yarn test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
